config/routes.rb
Rails.application.routes.draw do
  get 'races/index'
  get 'races/show'
  get 'races/edit'
  get 'races/update'
  get 'races/destroy'
  get 'races/new'
  get 'races/create'
  root "pages#home"
  devise_for :users, controllers: { registrations: "registrations" }
  resources :organisations
  resources :races
  get "/welcome", to: "pages#welcome", as: "welcome"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/organisation.rb
class Organisation < ApplicationRecord
  mount_uploader :logo, AvatarUploader
  belongs_to :user
  validates :name, presence: true, length: { minimum: 3, maximum: 30 }
  validates :user, uniqueness: true
  validates :phone, presence: true, length: { minimum: 3, maximum: 30 }, allow_blank: true
  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :description, presence: true, length: { minimum: 10, maximum: 600 }
  validates :location, presence: true
  geocoded_by :location
  after_validation :geocode
end

app/models/photo.rb
class Photo < ApplicationRecord
end

app/models/race.rb
class Race < ApplicationRecord
  mount_uploader :cover_picture, CoverPictureUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable,  and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  has_one :organisation

  def organiser?
    self.organisation && self.organisation.id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  before_action :set_organisation, only: [:edit, :update, :show]

  def index
  end

  def new
    @organisation = Organisation.new
  end

  def show
  end

  def create
    @organisation = Organisation.new(organisation_params)
    @organisation.user = current_user
    if @organisation.save
      flash[:success] = "La tua organizzazione è stata inserita!"
      redirect_to new_race_path
    else
      flash[:alert] = "Ops, c'è un errore nel form. Per favore controlla :)"
      render :new
    end
  end

  def destroy
  end

  def edit
  end

  def update
  end

  private

  def set_organisation
    @organisation = Organisation.find(params[:id])
  end

  def organisation_params
    params.require(:organisation).permit(:name, :email, :phone, :logo, :location, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/races_controller.rb
require "mini_magick"

class RacesController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def new
    @race = Race.new
  end

  def create
    @race = Race.new
    img = params[:race][:cover_picture].tempfile.to_path
    image = MiniMagick::Image.open(img)
    @race.cover_picture = image.crop set_photo_size(params)
    @race.save
  end

  def set_photo_size(params)
    width = params[:photo][:width]
    height = params[:photo][:height]
    xoffset = params[:photo][:xoffset]
    yoffset = params[:photo][:yoffset]
    "#{width}x#{height}+#{xoffset}+#{yoffset}"
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    (resource.sign_in_count > 1 || resource.organisation) ? root_path : welcome_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trailcalendar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag  'application', media: 'all' %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link  href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.4/cropper.min.css" rel="stylesheet">

  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/alerts" %>
    <%= yield %>
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>

app/views/organisations/create.html.erb
<h1>Organisations#create</h1>
<p>Find me in app/views/organisations/create.html.erb</p>

app/views/organisations/delete.html.erb
<h1>Organisations#delete</h1>
<p>Find me in app/views/organisations/delete.html.erb</p>

app/views/organisations/edit.html.erb
<h1>Organisations#edit</h1>
<p>Find me in app/views/organisations/edit.html.erb</p>

app/views/organisations/index.html.erb
<h1>Organisations#index</h1>
<p>Find me in app/views/organisations/index.html.erb</p>

app/views/organisations/new.html.erb
<%= render "shared/alerts" %>
<div class="container pb-5">
<h1>Inserisci il tuo gruppo</h1>
  <div class="row py-4">
    <div class="col-md-10 mx-auto">
        <%= simple_form_for @organisation do |f| %>
          <%= f.input :name, label:"Nome del gruppo" %>
          <%= f.input :email, label: "Indirizzo email" %>
          <%= f.input :phone, label: "Numero di telefono", type:"tel"%>
          <%= f.input :location, label: "Dove ha sede il gruppo?" %>
          <%= f.input :description, label: "Racconta qualcosa sul tuo gruppo sportivo.", :input_html => { :rows => 7 , :style => 'width: 100%'}%>
          <div class="d-flex">
            <%= f.input :logo, label: "Logo del gruppo", input_html: { accept: ".jpg, .gif, .png" } %>
            <img class="img-preview" id="logo-prewiew"/>
            <%= f.input :logo_cache, as: :hidden %>
          </div>
          <%= f.submit "Conferma", class: "btn btn-primary"%>
        <% end %>
    </div>
  </div>
</div>

app/views/organisations/show.html.erb
<h1><%= @organisation.name %></h1>

<%= link_to "Add a Race", new_race_path %>

app/views/organisations/update.html.erb
<h1>Organisations#update</h1>
<p>Find me in app/views/organisations/update.html.erb</p>

app/views/pages/home.html.erb
<div class="container">
  <h1>Header 1</h1>
  <h2>Header 2</h2>
  <h3>Header 3</h3>
  <p>Paragraph</p>
</div>

<div class="container">
   <div class="row">
     <div class="col-md-6 col-lg-4">
        <div class="card">
          <div class="race-card-date">
            <p class="race-card-date-day">10</p>
            <p>August</p>
          </div>
          <img class="card-img" src="https://picsum.photos/id/141/300/300" alt="">
          <div class="p-2">
            <div class="race-card-info"><i class="mr-1 fas fa-map-marker"></i>CORTENO GOLGI, BS</div>
            <div class="race-title">Sentiero 4 luglio Sky Marathon</div>
            <div class="race-card-info">Skyrunning | 43km | 3000m d+</div>
          </div>
        </div>
     </div>
   </div>
</div>

app/views/pages/welcome.html.erb
<%= link_to "Add your organisation" , new_organisation_path%>

<%= link_to "Search the races" %>

app/views/races/_race_price_selection.html.erb
          <div class="accordion my-4" id="racePriceSelector">
          <label for="">Inserisci il prezzo dell'iscrizione. Se la tua gara ha un prezzo unico, clicca sul primo plsant e inseriscilo. Se invece offri inscrizioni a prezzi differenti in base al perido, clicca il secondo pulsante. </label>
            <button class="btn btn-secondary" type="button" data-toggle="collapse" data-target="#singlePrice" aria-expanded="true" aria-controls="singlePrice">
              Prezzo unico
            </button>
            <button class="btn btn-secondary" type="button" data-toggle="collapse" data-target="#multiplePrice" aria-expanded="true" aria-controls="multiplePrice">
              Differente 
            </button>
            <div id="singlePrice" class="collapse" aria-labelledby="headingOne" data-parent="#racePriceSelector">
              <div class="card-body">
              <%= f.input :final_price, label: "Prezzo dell'iscrizione", input_html: { min: '0', max: '400', step: 'any' }%>
              </div>
            </div>
            <div id="multiplePrice" class="collapse " aria-labelledby="headingOne" data-parent="#racePriceSelector">
              <div class="card-body">
              <% ["first_price", "second_price", "third_price"].each_with_index do |price, index| %>
                <% words = ["Prima", "Seconda", "Terza"] %>
            <div class="row" id="price-<%=index%>">
              <div class="col-md-4">
                <%= f.input "#{price}".to_sym, label: "#{words[index]} fascia di prezzo - #{"€" * (index + 1)}"%> 
              </div>
              <div class="col-md-8">
                <%= f.input "#{price}_start".to_sym, label: "Prezzo valido dal al...", input_html: { min: '0', max: '1000' ,step: 'any' , class: 'date-range',  :data => {:step => "#{index}"}, placeholder: "Seleziona il periodo..."}%> 
              </div>
            </div>     
          <% end %>

              </div>
            </div>
          </div>

app/views/races/create.html.erb
<h1>Races#create</h1>
<p>Find me in app/views/races/create.html.erb</p>

app/views/races/destroy.html.erb
<h1>Races#destroy</h1>
<p>Find me in app/views/races/destroy.html.erb</p>

app/views/races/edit.html.erb
<h1>Races#edit</h1>
<p>Find me in app/views/races/edit.html.erb</p>

app/views/races/index.html.erb
<h1>Races#index</h1>
<p>Find me in app/views/races/index.html.erb</p>

app/views/races/new.html.erb
<div class="container pb-5">
  <h1>Inserisci una tua gara</h1>
  <div class="row py-4">
    <div class="col-md-10 mx-auto">
      <%= simple_form_for @race do |f| %>
      <%= f.input :name, label:"Nome della corsa" %>
      <div class="row">
        <div class="col-md-6">
          <%= f.input :length, label: "Distanza in Km", input_html: { min: '0', max: '400', step: '1' }%>
        </div>
        <div class="col-md-6">
          <%= f.input :elevation, label: "Dislivello positivo in m", input_html: { min: '0', max: '30000', step: '50' }%>
        </div>
      </div>
      <label for="">Tipo di Gara</label>
      <div class="d-flex justify-content-around flex-wrap my-4">
        <button type="button" class="btn race-type-btn">Trail</button>
        <button type="button" class="btn race-type-btn">Ultra Trail</button>
        <button type="button" class="btn race-type-btn">Skyrace</button>
        <button type="button" class="btn race-type-btn">Vertical</button>
      </div>
      <%= f.hidden_field :race_type, label: "Tipologia" %>
      <%= f.input :location, label: "Località - Da dove parte la gara?"%>
      <div class="row">
        <div class="col-md-6">
          <%= f.input :date, label: "Data dell'evento", html5: true, input_html: { class: 'date-simple', placeholder: "Seleziona la data..." }  %>
        </div>
        <div class="col-md-6">
          <%= f.input :departure_time, label: "Orario di Partenza",  html5: true,  input_html: { class: 'date-hour', placeholder: "Seleziona l'orario..." }  %>
        </div>
      </div>
      <%= f.input :description, label: "Descrizione della corsa.", :input_html => { :rows => 9 , :style => 'width: 100%'} %>

      <%= render "race_price_selection", f: f %>
      <input id="img-width" type="number" name=photo[width] hidden="true"> 
      <input id ="img-height" type="number" name=photo[height] hidden="true"> 
      <input id ="xoffset" type="number" name=photo[xoffset] hidden="true"> 
      <input id ="yoffset" type="number" name=photo[yoffset] hidden="true"> 
      <%= f.input :goodies, label: "Pacco gara (Se presente)", :input_html => { :rows => 6 , :style => 'width: 100%'} %>
      <%= f.submit "Conferma", class: "btn btn-primary"%>
      <div class="d-flex">
        <%= f.input :cover_picture, label: "Immagine di copertina (Dimensione ottimale 1153*367)", input_html: { accept: ".jpg, .gif, .png" } %>
        
      </div>
        <%= f.input :cover_picture_cache, as: :hidden %>
      <% end %>
    </div>
  </div>
</div>

<div class="modal fade" id="imagePreviewModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <div id="previewImgBody">
        <img class="img-preview" id="cover-image-prewiew" />
      </div>
      </div>
      <div class="modal-footer">
        <button id="closeCropper" type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" id="confirm-crop" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>



<%= javascript_pack_tag "flatpickr_init.js" %>
<%= javascript_pack_tag "new_race_form.js" %>

app/views/races/show.html.erb
<h1>Races#show</h1>
<p>Find me in app/views/races/show.html.erb</p>

app/views/races/update.html.erb
<h1>Races#update</h1>
<p>Find me in app/views/races/update.html.erb</p>

app/views/shared/_alerts.html.erb
<% if flash[:alert]%>
  <div data-type="warning" data-message="<%= flash[:alert]  %> " id="alertBox"></div>
<% elsif flash[:success] %>
  <div data-type="success" data-message="<%= flash[:success]  %> " id="alertBox"></div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class=" justify-content-end collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
    <% if user_signed_in? %>
      <li class="nav-item active">
        <%= link_to "Logout", destroy_user_session_path, class:"nav-link", method: :delete %>
      </li>
      <% if current_user.organiser? %>
      <li class="nav-item active">
        <%= link_to "Your organisation", organisation_path(current_user.organisation), class:"nav-link" %>
      </li>

      <% end %>
    <% else %>       
      <li class="nav-item active">
        <%= link_to "Login", new_user_session_path, class:"nav-link" %>
      </li>
    <ul class="navbar-nav">
        <li class="nav-item active">
        <%= link_to "Register", new_user_registration_path, class:"nav-link" %>
        </li>
    <% end %>
    </ul>
  </div>
</nav>